apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: playback-order
  description: Playback Order
  tags:
    - java
    - playback
  annotations:
    ilert.com/integration-key: il1crx0521d4e60d9d733c42ecba9e011a6d3d2427a7068b5e35
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: audio-playback
